# Support Vector Machine
## Cost Function: min(w,b) ||w||^2/2   and constraint =>  y_i * W.T + b >= 1 Soft Margin
## Cost Function: min(w,b) ||w||^2/2 + C.Sigma_1_w(E.e_i)  Hard Margin , C: 1/misclassification allowed  
- C.sigma_1_w(E.e_i) : slack penalty,  E - Slack variable i.e degree of violation calculated as the sum of distanceof misclassified point from the margin hyperplane
## Kernel function:
- Function

In [10]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [5]:
df = datasets.load_iris(as_frame=True).frame
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [6]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [8]:
X = df.drop("target", axis=1)
y = df["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [20]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [22]:
svm =  SVC()
svm.fit(X_train_scaled, y_train)
y_pred = svm.predict(X_test_scaled)
print(f'Accuracy Score : {accuracy_score(y_test, y_pred)}')
# print(f'F1 Score : {f1_score(y_test, y_pred)}')
print("Classification Report\n", classification_report(y_test, y_pred))

Accuracy Score : 0.9333333333333333
Classification Report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [24]:
# Linear Kernel
svm = SVC(kernel="linear")
svm.fit(X_train_scaled, y_train)
y_pred = svm.predict(X_test_scaled)
print(f"Accuracy Score : {accuracy_score(y_test, y_pred)}")

Accuracy Score : 0.9111111111111111

In [25]:
# Linear Kernel
svm = SVC(kernel="poly")
svm.fit(X_train_scaled, y_train)
y_pred = svm.predict(X_test_scaled)
print(f"Accuracy Score : {accuracy_score(y_test, y_pred)}")

Accuracy Score : 0.8666666666666667

In [26]:
# Sigmoid Kernel
svm = SVC(kernel="sigmoid")
svm.fit(X_train_scaled, y_train)
y_pred = svm.predict(X_test_scaled)
print(f"Accuracy Score : {accuracy_score(y_test, y_pred)}")

Accuracy Score : 0.9111111111111111

In [39]:
# linear HyperParameter tuning
c_vals = [0.125, 0.25, 0.3, 0.5, 0.7, 1, 1.2, 1.5, 2, 3, 4, 5]
for c_val in c_vals:
    svm = SVC(C=c_val, kernel="rbf")
    svm.fit(X_train_scaled, y_train)
    y_pred = svm.predict(X_test_scaled)
    print(f"AT C = {c_val} we get Accuracy Score : {accuracy_score(y_test, y_pred)}")

AT C = 0.125 we get Accuracy Score : 0.8888888888888888
AT C = 0.25 we get Accuracy Score : 0.9111111111111111
AT C = 0.3 we get Accuracy Score : 0.9111111111111111
AT C = 0.5 we get Accuracy Score : 0.9111111111111111
AT C = 0.7 we get Accuracy Score : 0.9333333333333333
AT C = 1 we get Accuracy Score : 0.9333333333333333
AT C = 1.2 we get Accuracy Score : 0.9111111111111111
AT C = 1.5 we get Accuracy Score : 0.9111111111111111
AT C = 2 we get Accuracy Score : 0.9111111111111111
AT C = 3 we get Accuracy Score : 0.9111111111111111
AT C = 4 we get Accuracy Score : 0.9333333333333333
AT C = 5 we get Accuracy Score : 0.9333333333333333