In [9]:
import pandas as pd
from sklearn import datasets
from sklearn.metrics import r2_score
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split, 
from sklearn.preprocessing import StandardScaler

In [5]:
df = datasets.load_diabetes(as_frame=True).frame
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [7]:
X = df.drop("target", axis=1)
y = df["target"]
y.head()

0    151.0
1     75.0
2    141.0
3    206.0
4    135.0
Name: target, dtype: float64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
225,0.030811,0.050680,0.032595,0.049415,-0.040096,-0.043589,-0.069172,0.034309,0.063015,0.003064
412,0.074401,-0.044642,0.085408,0.063187,0.014942,0.013091,0.015505,-0.002592,0.006207,0.085907
118,-0.056370,0.050680,-0.010517,0.025315,0.023198,0.040022,-0.039719,0.034309,0.020609,0.056912
114,0.023546,-0.044642,0.110198,0.063187,0.013567,-0.032942,-0.024993,0.020655,0.099241,0.023775
364,0.001751,0.050680,-0.006206,-0.019442,-0.009825,0.004949,-0.039719,0.034309,0.014821,0.098333

In [11]:
y_scaler = StandardScaler()
y_train_scaled = y_scaler.fit_transform(y_train.values.reshape(-1,1)).ravel()
y_test_scaled = y_scaler.transform(y_test.values.reshape(-1,1)).ravel()
y_train.head()

225    208.0
412    261.0
118    179.0
114    258.0
364    262.0
Name: target, dtype: float64

In [14]:
model = SVR()
model.fit(X_train, y_train_scaled)
y_train_pred_scaled = model.predict(X_train)
y_test_pred_scaled = model.predict(X_test)
print("Train R2 Score : ",r2_score(y_train_scaled, y_train_pred_scaled))
print("Test R2 Score : ",r2_score(y_test_scaled, y_test_pred_scaled))

Train R2 Score :  0.6596361676267712
Test R2 Score :  0.48844443151651884

In [15]:
model = SVR(kernel="linear")
model.fit(X_train, y_train_scaled)
y_train_pred_scaled = model.predict(X_train)
y_test_pred_scaled = model.predict(X_test)
print("Train R2 Score : ",r2_score(y_train_scaled, y_train_pred_scaled))
print("Test R2 Score : ",r2_score(y_test_scaled, y_test_pred_scaled))

Train R2 Score :  0.45191229982475245
Test R2 Score :  0.4433761323833776

In [16]:
model = SVR(kernel="poly")
model.fit(X_train, y_train_scaled)
y_train_pred_scaled = model.predict(X_train)
y_test_pred_scaled = model.predict(X_test)
print("Train R2 Score : ",r2_score(y_train_scaled, y_train_pred_scaled))
print("Test R2 Score : ",r2_score(y_test_scaled, y_test_pred_scaled))

Train R2 Score :  0.579092083431054
Test R2 Score :  0.24203771038107802