In [1]:
import pandas as pd
import numpy as np

import re

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
print("Shape => ",df.shape)
df.isnull().sum()

Shape =>  (50000, 2)

review       0
sentiment    0
dtype: int64

In [4]:
df.drop_duplicates(inplace=True)
df.shape

(49582, 2)

In [5]:
# Lower str
df["review"].str.lower()

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 49582, dtype: object

In [6]:
# Removing url
def remove_urls(text):
    text = re.sub(r"https\S+", "", text)  # (pattern, repl, string) eg: https://www.google.com
    return text
df["review"] = df["review"].apply(remove_urls)
print(df.shape)
df["review"]

(49582, 2)

0        One of the other reviewers has mentioned that ...
1        A wonderful little production. <br /><br />The...
2        I thought this was a wonderful way to spend ti...
3        Basically there's a family where a little boy ...
4        Petter Mattei's "Love in the Time of Money" is...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot, bad dialogue, bad acting, idiotic di...
49997    I am a Catholic taught in parochial elementary...
49998    I'm going to have to disagree with the previou...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 49582, dtype: object

In [7]:
# removing punctuations
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]", "", text)   # [] -> excluding this 
    return text

df["review"] = df["review"].apply(remove_punctuations)
df["review"]

0        One of the other reviewers has mentioned that ...
1        A wonderful little production br br The filmin...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 49582, dtype: object

In [8]:
# removing html
# . -> any one character must be present , * -> means zero or more character exists
def remove_html(text):
    text = re.sub(r"<.*?>", "", text)
    return text
df["review"] = df["review"].apply(remove_html)
df["review"]

0        One of the other reviewers has mentioned that ...
1        A wonderful little production br br The filmin...
2        I thought this was a wonderful way to spend ti...
3        Basically theres a family where a little boy J...
4        Petter Matteis Love in the Time of Money is a ...
                               ...
49995    I thought this movie did a down right good job...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I am a Catholic taught in parochial elementary...
49998    Im going to have to disagree with the previous...
49999    No one expects the Star Trek movies to be high...
Name: review, Length: 49582, dtype: object

In [9]:
# !conda install -y nltk

In [10]:
# conda update -n base -c defaults conda

In [11]:
import nltk

# nltk.download("punkt")
# nltk.download("punkt_tab")
# nltk.download("stopwords")

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

In [12]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")
    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [13]:
df

                                                  review sentiment
0      One    reviewers  ntied   wtchg  1 Oz epode ll...  positive
1      A wderful ltle producti br br T filming techni...  positive
2      I thought    wderful wy  spend time   o hot su...  positive
3      Bsclly res  fmly   lttle boy Jke thks res  zom...  negative
4      Petter Mtte Love   Time  Mey   vully stunng fi...  positive
...                                                  ...       ...
49995  I thought  move    rght good job It wsnt s cre...  positive
49996  Bd plot bd dilogue bd cting idiotic directing ...  negative
49997  I   Ctholic tught  prochil elentry schools  nu...  negative
49998  Im gog    dgree   previous comnt  side  Mlt   ...  negative
49999  No one expects  Str Trek movies   high rt   fn...  negative

[49582 rows x 2 columns]

In [14]:
def stemming(text):
    stemmed_words = []
    ps = PorterStemmer()
    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)  # appending each stemmedtoken to list of stemmed word 

    return " ".join(stemmed_words)  # converting list to string using join

df["review"] = df["review"].apply(stemming)
df

                                                  review sentiment
0      one review nti wtchg 1 oz epod ll hook they ri...  positive
1      a wder ltle producti br br t film techniqu uns...  positive
2      i thought wder wy spend time o hot summer week...  positive
3      bsclli re fmli lttle boy jke thk re zomb close...  negative
4      petter mtte love time mey vulli stunng film wt...  positive
...                                                  ...       ...
49995  i thought move rght good job it wsnt s cretv g...  positive
49996  bd plot bd dilogu bd cting idiot direct nnoy p...  negative
49997  i ctholic tught prochil elentri school nun tug...  negative
49998  im gog dgree previou comnt side mlt e th secd ...  negative
49999  no one expect str trek movi high rt fn expect ...  negative

[49582 rows x 2 columns]

In [15]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])
y = df["sentiment"]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4306699 stored elements and shape (49582, 5000)>

In [17]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4306699 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 2987)	0.0341727908152829
  (0, 3558)	0.05535426797838416
  (0, 2918)	0.13875034270953907
  (0, 4949)	0.09234670562566201
  (0, 3033)	0.47712494799530675
  (0, 1344)	0.12186448303347251
  (0, 2388)	0.05302560422451421
  (0, 1982)	0.08006528617006585
  (0, 4353)	0.05695828155504384
  (0, 3584)	0.09283766346432397
  (0, 1425)	0.06256444220622695
  (0, 2006)	0.06222123070719788
  (0, 315)	0.08676660912641725
  (0, 4348)	0.05195356608210433
  (0, 1557)	0.07108354563207131
  (0, 4355)	0.03349202135189689
  (0, 4153)	0.17967926291585545
  (0, 3690)	0.033896378794476774
  (0, 4720)	0.2578495845121279
  (0, 3794)	0.04466049036631505
  (0, 4767)	0.058637486663262954
  (0, 1788)	0.037580844040655446
  (0, 4509)	0.07691771134050528
  (0, 3843)	0.17434821186406638
  (0, 1684)	0.0676975124821042
  :	:
  (49581, 2880)	0.09803035445944089
  (49581, 513)	0.11267505834011247
  (49581, 4255)	0.10924628649491637
  (49581, 2003)	0.09339189744686417
  (49581, 632)	0.08423554725415285
  (49581, 2891)	0.11645501219067643
  (49581, 2311)	0.09527262061788769
  (49581, 4321)	0.16830984354455947
  (49581, 4640)	0.11591069954383258
  (49581, 3653)	0.09058149379828939
  (49581, 4740)	0.1254346597572933
  (49581, 2015)	0.12792239889375384
  (49581, 2114)	0.16867559502289947
  (49581, 610)	0.11425052631246936
  (49581, 2274)	0.13339212050648758
  (49581, 4468)	0.15980651289457978
  (49581, 2262)	0.18389977411478797
  (49581, 4023)	0.20094981375857346
  (49581, 3505)	0.1618051160299912
  (49581, 425)	0.14814624357491923
  (49581, 2767)	0.17396425176349883
  (49581, 4985)	0.13558369808984214
  (49581, 517)	0.13329673752750715
  (49581, 1811)	0.1579498698576169
  (49581, 3506)	0.15180673113782556

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
X_train

(39665, 5000)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3447094 stored elements and shape (39665, 5000)>

In [19]:
print(y_test.shape)
y_test

(9917,)

29171    0
43589    1
38712    0
16045    0
5248     1
        ..
2923     1
15292    0
17849    0
38079    0
2691     0
Name: sentiment, Length: 9917, dtype: int64

In [20]:
X_test
type(y_train)

pandas.core.series.Series

In [21]:
X_train = X_train.toarray()   # toarray() : this could convert sparse mattrix to numpy array.
X_test = X_test.toarray()

In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [23]:
train_set = TensorDataset(torch.from_numpy(X_train).float(), torch.from_numpy(y_train.values).float())
train_set

In [24]:
test_set = TensorDataset(torch.from_numpy(X_test).float(), torch.from_numpy(y_test.values).float())
test_set

In [36]:
train_loader = DataLoader(train_set, batch_size=64, shuffle=True)
test_loader = DataLoader(test_set, batch_size=64, shuffle=True)
train_loader

In [56]:
# batch, sequence and input_size
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()
        self.hidden_size=hidden_size
        self.num_layers=num_layers

        # RNN is present inside the torch.nn
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        self.fc = nn.Linear(hidden_size, 1)

    
    def forward(self, x):

        # h0 hidden size
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        # RNN : 2 outputs, 1> total hiddensize of all time steps and 2> final hiddensize of last timestep only
        out, _  = self.rnn(x, h0)   # dimensions of out => (batch_size, seq_len, hidden_size)

        # print("out : ",out)
        # print("out last : ",out[:,-1, :])
        
        # fc
        out = self.fc(out[:, -1, :])
        return out

Epoch No. 1 and loss => 228.50972859561443
Epoch No. 2 and loss => 157.07305125147104
Epoch No. 3 and loss => 147.4466858357191
Epoch No. 4 and loss => 142.49608109891415
Epoch No. 5 and loss => 140.02274005115032
Epoch No. 6 and loss => 138.08692432940006
Epoch No. 7 and loss => 136.6293896883726
Epoch No. 8 and loss => 135.37627571076155
Epoch No. 9 and loss => 134.84178657084703
Epoch No. 10 and loss => 133.8638240918517

Accuracy Score : 86.23575678128466 %